project_id = "wkhgnavkcwdhzvgqbuvo"

[functions.analyze-room]
verify_jwt = false

[functions.paint-wall]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-auth-link]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.paint-wall-replicate]
verify_jwt = false

[functions.test-replicate]
verify_jwt = false

[functions.paint-wall-replicate-simple]
verify_jwt = false

[functions.paint-wall-replicate-debug]
verify_jwt = false

[functions.get-token]
verify_jwt = false

[functions.get-local-token]
verify_jwt = false
